### ISSUE TITLE
Power strips for LIB 1001

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/upper-division-cs#1346]
A few students mentioned running out of power during class, only the seats near the walls have access to the outlets.

I added this request to our space request on schedule.evergreen.edu
and I'll keep looking if there's a Building Facilities department or a more appropriate office to help with this.

**Comment by faulkdf** [comment]
Is there any way we can have one of the SEM II classrooms? Those spaces are more comfortable, easier to see and hear the lecture and slides, and the lecture hall spaces on the bottom floor have power built into the tables. 

I would be surprised if all of those spaces are occupied, especially since we were able to use SEM II A1105 for the first week.

**Comment by learner-long-life** [comment]
Moved to SEM II C 1105 for rest of quarter.
